### ISSUE TITLE
MostPopular baseline model is not properly counting the scores from events input

### ISSUE THREAD

**Issue by svacha** [takuti/Recommendation.jl#16]
Running a sequence of commands from the Getting Started page in the docs:
```
n_user, n_item = 5, 10
events = [Event(1, 2, 1), Event(3, 2, 1), Event(2, 6, 4)]
data = DataAccessor(events, n_user, n_item)
recommender = MostPopular(data)
build!(recommender)
```
Then running the recommend method for any user:
```
recommend(recommender, 4, 2, collect(1:n_item))
```
Yields:
```
Pair{Int64,Float64}
7=>5.0
4=>5.0
```
I would expect the top two recommendations to be item 2 and item 6 given the example input.

I'm not sure about the expected behavior for the non-initialized user-item values, but `recommender.data.R` looks like:
```
5×10 Array{Float64,2}:
 NaN    1.0  NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN
 NaN  NaN    NaN  NaN  NaN    4.0  NaN  NaN  NaN  NaN
 NaN    1.0  NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN
 NaN  NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN
 NaN  NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN
```
The problem seems to be with this line that counts the scores in the `MostPopular` model using the `iszero` method:
https://github.com/takuti/Recommendation.jl/blob/master/src/baseline/most_popular.jl#L25

I'm not exactly sure about the fix, but changing `!iszero` to `!isnan` produces the scores I would expect, or if the idea is to handle both zeros or NaNs, maybe something like:
```
recommender.scores[i] = [count(x->!(iszero(x) || isnan(x)), data.R[:, i]) for i in 1:n_item]
```

**Comment by svacha** [comment]
This was with Julia version v"1.5.1" and Recommendation version v"0.3.0".

**Comment by takuti** [comment]
Thank you @svacha for reporting the issue. Sorry for my late response.

#19 fixes the issue. In fact, as of 6031452283a5b466c7fff1246c138cfbdf73d935, missing values are represented by `undef`, which corresponds to a very small number. Hence, I just replaced `!iszero` with `>(1e-256)` so `MostPopular` doesn't mistakenly count both `0` and `undef`.
