### ISSUE TITLE
Julia version v1.0.3

### ISSUE THREAD

**Issue by tosolveit** [takuti/Recommendation.jl#4]
Hi, do you have plans to upgrade julia version for the package?

**Comment by takuti** [comment]
@tosolveit Thank you for reminding me. Indeed, since Julia version finally becomes 1.0, I will catch-up diff and try to upgrade this package as soon as possible.

**Comment by henry2004y** [comment]
I am using Julia version 1.0, and even though I saw the comments of v0.7+ support, I still get the error:

`ERROR: Unsatisfiable requirements detected for package Recommendation [d27d45ae]:
 Recommendation [d27d45ae] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left`

**Comment by takuti** [comment]
Released the latest version with Julia 1.0 support: https://github.com/JuliaLang/METADATA.jl/pull/20849

@tosolveit @henry2004y Can you try to use `Recommendation.jl` on your Julia environment?

```jl
julia> using Pkg
julia> Pkg.add("Recommendation")
```

**Comment by henry2004y** [comment]
Yep, it's working! Thanks!
