### ISSUE TITLE
Example in readme not working with 1.0.2

### ISSUE THREAD

**Issue by milanhej** [takuti/Recommendation.jl#5]
Using Julia v1.0.2 with the following code from the readme:

const n_user = 5
const n_item = 10

events = [Event(1, 2, 1), Event(3, 2, 1), Event(2, 6, 4)]
da = DataAccessor(events, n_user, n_item)

produces the error:

MethodError: no method matching DataAccessor(::Array{Event,1}, ::Int64, ::Int64)
Closest candidates are:
  DataAccessor(::Any, ::Any, ::Any, !Matched::Any) at /Users/research/.julia/packages/Recommendation/N3AeW/src/data_accessor.jl:5
  DataAccessor(!Matched::Array{Recommendation.Event,1}, ::Int64, ::Int64) at /Users/research/.julia/packages/Recommendation/N3AeW/src/data_accessor.jl:11

Stacktrace:
 [1] top-level scope at In[11]:5

**Comment by takuti** [comment]
How did you import the package? As far as I tested with Julia 1.0.3, it works correctly: 

```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3 (2018-12-18)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Recommendation

julia> const n_user = 5
5

julia> const n_item = 10
10

julia> events = [Event(1, 2, 1), Event(3, 2, 1), Event(2, 6, 4)]
3-element Array{Event,1}:
 Event(1, 2, 1.0)
 Event(3, 2, 1.0)
 Event(2, 6, 4.0)

julia> da = DataAccessor(events, n_user, n_item)
DataAccessor(Event[Event(1, 2, 1.0), Event(3, 2, 1.0), Event(2, 6, 4.0)], [NaN 1.0 … NaN NaN; NaN NaN … NaN NaN; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN], Dict{Int64,Any}(), Dict{Int64,Any}())
```

If you cannot see any differences, could you try the same thing with [Julia 1.0.3](https://julialang.org/downloads/) as well? I believe the [diff between 1.0.2 and 1.0.3](https://github.com/JuliaLang/julia/releases/tag/v1.0.3) is limited, and hence it'd be helpful to figure out a problematic part.

**Comment by milanhej** [comment]
Thanks for your reply.  I've upgraded to 1.1.0 and all works well in the REPL, though oddly enough not in IJulia, not sure why, but I can work around it.
