### ISSUE TITLE
may you share why you switched from python to julia?

### ISSUE THREAD

**Issue by Sandy4321** [takuti/Recommendation.jl#9]
may you share why you switched from python to julia?

good job 
https://hub.packtpub.com/how-to-make-machine-learning-based-recommendations-using-julia-tutorial/

**Comment by takuti** [comment]
@Sandy4321 Thank you for asking and sorry for taking too long to respond.

You could always refer to the following links for motivation:

- [My blog post](https://takuti.me/note/recommendation-julia/)
- [My JuliaCon 2019 talk](https://takuti.me/ja/work/juliacon-2019/)
